-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_aguia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_aguia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_aguia` DEFAULT CHARACTER SET utf8 ;
USE `projeto_aguia` ;

-- -----------------------------------------------------
-- Table `projeto_aguia`.`CATEGORIA_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`CATEGORIA_CLIENTE` (
  `id_CATEGORIA_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `nome_CATEGORIA_CLIENTES` VARCHAR(45) NOT NULL,
  `descricao_categ_cli` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_CATEGORIA_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`CLIENTES` (
  `id_CLIENTES` INT NOT NULL AUTO_INCREMENT,
  `senha_CLIENTES` VARCHAR(20) NOT NULL,
  `sexo_CLIENTES` VARCHAR(20) NOT NULL,
  `telefone_CLIENTES` VARCHAR(15) NOT NULL,
  `email_CLIENTES` VARCHAR(50) NOT NULL,
  `nome_CLIENTES` VARCHAR(45) NOT NULL,
  `sobrenome_CLIENTES` VARCHAR(45) NOT NULL,
  `cpf_CLIENTES` VARCHAR(14) NOT NULL,
  `status_CLIENTES` TINYINT NOT NULL,
  `CATEGORIA_CLIENTE_id_CATEGORIA_CLIENTE` INT NOT NULL,
  `ENDERECO_CLIENTE_id_ENDERECO_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`id_CLIENTES`),
  INDEX `fk_CLIENTES_CATEGORIA_CLIENTE1_idx` (`CATEGORIA_CLIENTE_id_CATEGORIA_CLIENTE` ASC) VISIBLE,
  INDEX `fk_CLIENTES_ENDERECO_CLIENTE1_idx` (`ENDERECO_CLIENTE_id_ENDERECO_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_CATEGORIA_CLIENTE1`
    FOREIGN KEY (`CATEGORIA_CLIENTE_id_CATEGORIA_CLIENTE`)
    REFERENCES `projeto_aguia`.`CATEGORIA_CLIENTE` (`id_CATEGORIA_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_ENDERECO_CLIENTE1`
    FOREIGN KEY (`ENDERECO_CLIENTE_id_ENDERECO_CLIENTE`)
    REFERENCES `projeto_aguia`.`ENDERECO_CLIENTE` (`id_ENDERECO_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`ENDERECO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`ENDERECO_CLIENTE` (
  `id_ENDERECO_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `cep_ENDERECO_CLIENTE` VARCHAR(8) NOT NULL,
  `complemento_ENDERECO_CLIENTE` VARCHAR(45) NOT NULL,
  `bairro_ENDERECO_CLIENTE` VARCHAR(45) NOT NULL,
  `casa_ENDERECO_CLIENTE` VARCHAR(45) NOT NULL,
  `rua_ENDERECO_CLIENTE` VARCHAR(45) NOT NULL,
  `CLIENTES_id_CLIENTES` INT NOT NULL,
  PRIMARY KEY (`id_ENDERECO_CLIENTE`),
  CONSTRAINT `fk_CLIENTES_id_CLIENTES`
    FOREIGN KEY (`CLIENTES_id_CLIENTES`)
    REFERENCES `projeto_aguia`.`CLIENTES` (`id_CLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projeto_aguia`.`SETOR_FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`SETOR_FUNCIONARIOS` (
  `id_SETOR_FUNCIONARIOS` INT NOT NULL AUTO_INCREMENT,
  `nome_SETOR_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `descricao_setor` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_SETOR_FUNCIONARIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`FUNCIONARIOS` (
  `id_FUNCIONARIOS` INT NOT NULL AUTO_INCREMENT,
  `senha_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `login_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `telefone_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `email_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `sexo_FUNCIONARIOS` VARCHAR(20) NOT NULL,
  `nome_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `SETOR_FUNCIONARIOS_id_SETOR_FUNCIONARIOS` INT NOT NULL,
  PRIMARY KEY (`id_FUNCIONARIOS`),
  INDEX `fk_FUNCIONARIOS_SETOR_FUNCIONARIOS1_idx` (`SETOR_FUNCIONARIOS_id_SETOR_FUNCIONARIOS` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIOS_SETOR_FUNCIONARIOS1`
    FOREIGN KEY (`SETOR_FUNCIONARIOS_id_SETOR_FUNCIONARIOS`)
    REFERENCES `projeto_aguia`.`SETOR_FUNCIONARIOS` (`id_SETOR_FUNCIONARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`ENDERECO_FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`ENDERECO_FUNCIONARIOS` (
  `id_ENDERECO_FUNCIONARIOS` INT NOT NULL AUTO_INCREMENT,
  `cep_ENDERECO_FUNCIONARIOS` VARCHAR(8) NOT NULL,
  `complemento_ENDERECO_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `bairro_ENDERECO_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `casa_ENDERECO_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `rua_ENDERECO_FUNCIONARIOS` VARCHAR(45) NOT NULL,
  `FUNCIONARIOS_id_FUNCIONARIOS` INT NOT NULL,
  PRIMARY KEY (`id_ENDERECO_FUNCIONARIOS`, `FUNCIONARIOS_id_FUNCIONARIOS`),
  INDEX `fk_ENDERECO_FUNCIONARIOS_FUNCIONARIOS1_idx` (`FUNCIONARIOS_id_FUNCIONARIOS` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_FUNCIONARIOS_FUNCIONARIOS1`
    FOREIGN KEY (`FUNCIONARIOS_id_FUNCIONARIOS`)
    REFERENCES `projeto_aguia`.`FUNCIONARIOS` (`id_FUNCIONARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`PEDIDO` (
  `id_PEDIDO` INT NOT NULL AUTO_INCREMENT,
  `data_PEDIDO` DATETIME NOT NULL,
  `CLIENTES_id_CLIENTES` INT NOT NULL,
  `FUNCIONARIOS_id_FUNCIONARIOS` INT NULL,
  PRIMARY KEY (`id_PEDIDO`),
  INDEX `fk_PEDIDO_CLIENTES1_idx` (`CLIENTES_id_CLIENTES` ASC) VISIBLE,
  INDEX `fk_PEDIDO_FUNCIONARIOS1_idx` (`FUNCIONARIOS_id_FUNCIONARIOS` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTES1`
    FOREIGN KEY (`CLIENTES_id_CLIENTES`)
    REFERENCES `projeto_aguia`.`CLIENTES` (`id_CLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_FUNCIONARIOS1`
    FOREIGN KEY (`FUNCIONARIOS_id_FUNCIONARIOS`)
    REFERENCES `projeto_aguia`.`FUNCIONARIOS` (`id_FUNCIONARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`CATEGORIA_PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`CATEGORIA_PRODUTOS` (
  `id_CATEGORIA_PRODUTOS` INT NOT NULL AUTO_INCREMENT,
  `nome_CATEGORIA_PRODUTOS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_CATEGORIA_PRODUTOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`PRODUTOS` (
  `id_PRODUTOS` INT NOT NULL AUTO_INCREMENT,
  `nome_PROTUDOS` VARCHAR(45) NOT NULL,
  `valor_PROTUDOS` FLOAT NOT NULL,
  `descricao_PROTUDOS` LONGTEXT NOT NULL,
  `quantidade_estoque_PROTUDOS` INT NOT NULL,
  `CATEGORIA_PRODUTOS_id_CATEGORIA_PRODUTOS` INT NOT NULL,
  PRIMARY KEY (`id_PRODUTOS`, `CATEGORIA_PRODUTOS_id_CATEGORIA_PRODUTOS`),
  INDEX `fk_PRODUTOS_CATEGORIA_PRODUTOS1_idx` (`CATEGORIA_PRODUTOS_id_CATEGORIA_PRODUTOS` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTOS_CATEGORIA_PRODUTOS1`
    FOREIGN KEY (`CATEGORIA_PRODUTOS_id_CATEGORIA_PRODUTOS`)
    REFERENCES `projeto_aguia`.`CATEGORIA_PRODUTOS` (`id_CATEGORIA_PRODUTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_aguia`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_aguia`.`COMPRA` (
  `PRODUTOS_id_PRODUTOS` INT NOT NULL,
  `PEDIDO_id_PEDIDO` INT NOT NULL,
  `quantidade_PEDIDO` INT NOT NULL,
  `valor_compra` DECIMAL NOT NULL,
  PRIMARY KEY (`PRODUTOS_id_PRODUTOS`, `PEDIDO_id_PEDIDO`),
  INDEX `fk_PRODUTOS_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_id_PEDIDO` ASC) VISIBLE,
  INDEX `fk_PRODUTOS_has_PEDIDO_PRODUTOS1_idx` (`PRODUTOS_id_PRODUTOS` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTOS_has_PEDIDO_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_id_PRODUTOS`)
    REFERENCES `projeto_aguia`.`PRODUTOS` (`id_PRODUTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTOS_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_PEDIDO`)
    REFERENCES `projeto_aguia`.`PEDIDO` (`id_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
